// <auto-generated />
namespace FlightNode.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoleDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201510270342542_Role-Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
